### PR TITLE
Digitial Certificate Check

### PR DESCRIPTION
**Pull request by pc-coholic**
Issues in no particular order:
- [x] `pretixscan-android` and `libpretixui-android` require a GitHub Personal Access Token
	- This is due to the fact, that GH registry required authentication
	- This will break CI and fdroid builds
	- Perhaps we can work around this using jitpack.io - a first experiment however failed
- [x] Initialization of DGC's `sdkDeps` happens in `pretixscan-android` instead of `libpretixui-android`. If we can move the init to the UI-lib, we can also kick the library-requirement from `pretixscan-android`.
- [x] pretix DGC validation rules are not applied as of now.
- [x] DGC uses exclusively the `assertGermanValidationRuleSet()` (to be replaced by the european ruleset in the DGC SDK). Either we accept this "as is" or try to dynamically implement validation rulesets.
- [x] Surface the results to the UI
- [x] Implement camerascan-handler --> Disabled for now
- [x] How do we decide the correct validator (DGC/Bärcode/...)?
	- We could probably try to decode the CBOR/COSE and check for known strings
	- We could also just use a try/catch-cascade until we arrive at a result/failure.
	- --> For now, we only do DGC
- [x] The Manifest.xml had to be adjusted, due to DGC shipping with their own `network_security_config.xml`. Either we find a workaround or make at least sure we're shipping our own, decent version of that file.
- [x] Do not use library on unsupported Android SDK < 23
- [ ] We have debugImplementation and releaseImplementation of the covpass-sdk and covpass-sdk-demo in the gradle build files. Unfortunately, in both cases the PROD (or nondemo) library seems to take precedence?
- [x] Tested against API-level lower than 23 (tested with: 22)

### CODE REVIEW

**Comment by raphaelm** [comment]
We probably also need to make sure we don't call the new library on Android versions where it is unsupported to avoid crashes

**Comment by pc-coholic** [comment]
Absolutely right... I knew I was forgetting something on my list up there...

**Comment by pc-coholic** [comment]
Well, the GH-CI/-Actions are now working.

The build is still failing however - but I feel like this should also happen on the main branch, although it isn't...

```
  /home/runner/work/pretixscan-android/pretixscan-android/pretixscan/app/src/main/java/eu/pretix/pretixscan/droid/ui/MainActivity.kt:301: Error: Overriding method should call super.onRequestPermissionsResult [MissingSuperCall]
      override fun onRequestPermissionsResult(requestCode: Int,
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~
  /home/runner/work/pretixscan-android/pretixscan-android/pretixscan/app/src/main/java/eu/pretix/pretixscan/droid/ui/SetupActivity.kt:101: Error: Overriding method should call super.onRequestPermissionsResult [MissingSuperCall]
      override fun onRequestPermissionsResult(requestCode: Int,
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~
  /home/runner/work/pretixscan-android/pretixscan-android/pretixscan/app/src/main/java/eu/pretix/pretixscan/droid/ui/WelcomeActivity.kt:39: Error: Overriding method should call super.onRequestPermissionsResult [MissingSuperCall]
      override fun onRequestPermissionsResult(requestCode: Int,
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by raphaelm** [comment]
> The build is still failing however - but I feel like this should also happen on the main branch, although it isn't...

I've seen this in other projects as well, I think the check was just recently added to the linter and we should just fix it.

**Comment by raphaelm** [comment]
done

**Pull request merged**
